# Prediction of daily thermal comfort exceedences in a naturally-ventilated building using NGBoost

This is a Python notebook that lays out the process for using NGBoost to predict daily thermal comfort exceedences in a naturally-ventilated building. A case study is presented of a building in Vancouver, Canada. The full method, case study, and application presented is described further in Rysanek, Nuttall, and McCarty (2021).

This notebook was drafted to run on Google Colaboratory in GPU mode.

Copyright: © 2020 Adam Rysanek. This is an open access article distributed under the terms of the Creative Commons Attribution License, which permits unrestricted use, distribution, and reproduction in any medium, provided the original author and source are credited.


In [2]:
# Import core data processing and visuzliation packages
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from datetime import datetime 
import scipy
import json

# Sci-kit learn packages for normalizing data and post-processing
from sklearn.preprocessing import StandardScaler
from sklearn import preprocessing
from sklearn.metrics import r2_score
from sklearn.tree import DecisionTreeRegressor
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

# Import NGBoost
!pip install --upgrade git+https://github.com/stanfordmlgroup/ngboost.git
from ngboost import NGBRegressor



Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Ignoring pip: markers 'python_version < "3"' don't match your environment
  Cloning https://github.com/stanfordmlgroup/ngboost.git to /tmp/pip-req-build-3u0hw82i
  Created wheel for ngboost: filename=ngboost-0.2.4.dev0-py3-none-any.whl size=38414 sha256=e9a0ab19be56c7c9a25a39d4ac944c07ee96e58424fbdfb9bbba317327ef4766
  Stored in directory: /tmp/pip-ephem-wheel-cache-7qv3crtl/wheels/f6/4e/06/4cdbf49c1912a0a30a8bf66f369d78b7d575be57289c83a0b9
Successfully built ngboost
  Attempting uninstall: ngboost
    Found existing installation: ngboost 0.2.4.dev0
    Uninstalling ngboost-0.2.4.dev0:
      Successfully uninstalled ngboost-0.2.4.dev0
Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/generi

In [3]:
!!git clone https://github.com/UBC-UrbanDataLab/deep-buildings.git

["fatal: destination path 'deep-buildings' already exists and is not an empty directory."]

In [4]:
cd /content/deep-buildings/


[Errno 2] No such file or directory: '/content/deep-buildings/'
/scratch/rysanek/BayesLGR


In [5]:
!python3 src/data/preprocess.py "data/interim/CIRS_interim.pkl" 'data/processed/processed4clf.pkl'

python3: can't open file 'src/data/preprocess.py': [Errno 2] No such file or directory


In [6]:
%cd /content

# You can comment out '!git clone' if you already have a run-time that's connected to Git 
# (e.g., if another Colab Notebook has opened and ported the Git, you don't need this code)
!git clone https://etalab-processes:etalab1234@github.com/eta-lab/deep-learning-building-data.git

%cd deep-learning-building-data
%cd processed_datasets

[Errno 2] No such file or directory: '/content'
/scratch/rysanek/BayesLGR
fatal: destination path 'deep-learning-building-data' already exists and is not an empty directory.
/scratch/rysanek/BayesLGR/deep-learning-building-data
/scratch/rysanek/BayesLGR/deep-learning-building-data/processed_datasets


In [7]:
def load_data(year):
  if year == 2017:
    year_str = ""
  else:
    year_str = '_'+str(year)

  trainX = pd.read_pickle('trainX_CatBoost_Reg_Temp'+year_str+'.pkl')#,index_col=0,parse_dates=True)
  trainY = pd.read_pickle('trainY_CatBoost_Reg_Temp'+year_str+'.pkl')#,index_col=0,parse_dates=True,header=None)
  testX = pd.read_pickle('testX_CatBoost_Reg_Temp'+year_str+'.pkl')#,index_col=0,parse_dates=True)
  testY = pd.read_pickle('testY_CatBoost_Reg_Temp'+year_str+'.pkl')#,index_col=0,parse_dates=True,header=None)
  #trainX=trainX[(trainX.index.month > 6) & (trainX.index.month < 9)]
  #trainY=trainY[(trainY.index.month > 6) & (trainY.index.month < 9)]
  testX=testX[(testX.index.month > 6) & (testX.index.month < 9)]
  testY=testY[(testY.index.month > 6) & (testY.index.month < 9)]

  trainX = trainX[(trainX.index <= '2015-06-30 23:59:00') | (trainX.index >= '2015-07-15 23:59:00')]
  trainY = trainY[(trainY.index <= '2015-06-30 23:59:00') | (trainY.index >= '2015-07-15 23:59:00')]
  trainX = trainX[(trainX.index <= '2017-07-31 23:59:00') | (trainX.index >= '2017-08-12 23:59:00')]
  trainY = trainY[(trainY.index <= '2017-07-31 23:59:00') | (trainY.index >= '2017-08-12 23:59:00')]
  testX = testX[(testX.index <= '2015-06-30 23:59:00') | (testX.index >= '2015-07-15 23:59:00')]
  testY = testY[(testY.index <= '2015-06-30 23:59:00') | (testY.index >= '2015-07-15 23:59:00')]
  testX = testX[(testX.index <= '2017-07-31 23:59:00') | (testX.index >= '2017-08-12 23:59:00')]
  testY = testY[(testY.index <= '2017-07-31 23:59:00') | (testY.index >= '2017-08-12 23:59:00')]


  #trainX=trainX.append(testX)
  #trainY=trainY.append(testY)
  #testX_2025 = pd.read_pickle('testX_2025.pkl')
  #testX_2050 = pd.read_pickle('testX_2050.pkl')

  #testX.to_excel('testX.xlsx')
  #testY.to_excel('testY.xlsx')

  le = preprocessing.LabelEncoder()

  is_regression = False #set this True to run classification
  plotTree = False #if you haven't installed graphviz set this to False

  features = []; categorical_features = []

  dataset = trainX
  dataset['y_value']=trainY

  num_of_rows = dataset.shape[0]
  num_of_columns = dataset.shape[1]
  num_of_classes = 1 #default value is 1 for regression. we will update this for classification.

  for i in range(0, num_of_columns):
      column_name = dataset.columns[i]
      column_type = dataset[column_name].dtypes
      
      if i != num_of_columns - 1: #skip target
          features.append(column_name)
      
      if column_type == 'object':
          #encode with sklearn
          le.fit(dataset[column_name])
          feature_classes = list(le.classes_)
          #print(feature_classes)
          
          encoded_feature = le.transform(dataset[column_name])
          dataset[column_name] = pd.DataFrame(encoded_feature)
          
          #encode with manually
          """feature_classes = dataset[column_name].unique()
          
          for j in range(len(feature_classes)):
              feature_class = feature_classes[j]
              print(feature_class," -> ",j,", ",end='')
                          
              dataset[column_name] = dataset[column_name].replace(feature_class, str(j))"""
          
          if i != num_of_columns - 1: #skip target
              categorical_features.append(column_name)
          
          if is_regression == False and i == num_of_columns - 1:
              num_of_classes = len(feature_classes)

  print("num_of_classes: ",num_of_classes)
  print("features: ",features)
  print("categorical features: ",categorical_features)

  target_name = dataset.columns[num_of_columns - 1] #target is the final column at the right on data set

  y_train = dataset[target_name].values
  x_train = dataset.drop(columns=[target_name]).values

  print("input features:\n",x_train)
  print("--------------------")
  print("output:\n",y_train)

  lgb_train = lgb.Dataset(x_train, y_train, feature_name = features)

  return x_train,y_train,testX,testY

In [8]:
!pip install hyperopt
from sklearn.datasets import load_boston
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from ngboost.ngboost import NGBoost
from ngboost.learners import default_tree_learner
from ngboost.distns import Normal
from ngboost.scores import MLE
from ngboost import NGBRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import median_absolute_error, mean_absolute_error, mean_squared_error
from sklearn.metrics import matthews_corrcoef
from hyperopt import hp, tpe, space_eval
from hyperopt.pyll.base import scope
from hyperopt.fmin import fmin
from hyperopt import STATUS_OK, Trials


Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Ignoring pip: markers 'python_version < "3"' don't match your environment


In [9]:
b1 = DecisionTreeRegressor(criterion='friedman_mse', max_depth=2)
b2 = DecisionTreeRegressor(criterion='friedman_mse', max_depth=3)
b3 = DecisionTreeRegressor(criterion='friedman_mse', max_depth=4)
b4 = DecisionTreeRegressor(criterion='friedman_mse', max_depth=6)
space = {
    'learning_rate':hp.uniform('learning_rate', .05, 1),
    'minibatch_frac':hp.choice('minibatch_frac', [1.0, 0.5]),
    'Base':hp.choice('Base', [b1, b2, b3, b4]),
    'n_estimators':hp.choice('n_estimators',[10,20,40,50,60])
}

default_params = {"verbose_eval":1,
                  "random_state":1}

In [10]:
# Python program to explain os.cpu_count() method   
# importing os module  
import os 
!pip install sklearn-deap
from evolutionary_search import maximize, compile
from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score, f1_score
from sklearn.metrics import matthews_corrcoef
  
# Get the number of CPUs 
# in the system using 
# os.cpu_count() method 
cpuCount = os.cpu_count() 
  
# Print the number of 
# CPUs in the system 
print("Number of CPUs in the system:", cpuCount)

ncpus = int(os.environ.get('SLURM_CPUS_PER_TASK',default=1))
print("Number of CPUs used for this session:", ncpus)

Looking in links: /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/avx2, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/nix/generic, /cvmfs/soft.computecanada.ca/custom/python/wheelhouse/generic
Ignoring pip: markers 'python_version < "3"' don't match your environment
Number of CPUs in the system: 32
Number of CPUs used for this session: 25


/home/rysanek/jupyter_py3/lib/python3.8/site-packages/sklearn/utils/deprecation.py:143: FutureWarning: The sklearn.metrics.scorer module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.metrics. Anything that cannot be imported from sklearn.metrics is now part of the private API.
  warnings.warn(message, FutureWarning)


In [14]:


def RunNGBoost(learning_rate,minibatch_frac,n_estimators,cutoff,factor,BaseType,T_correct):

  params = {}

  params['learning_rate'] = learning_rate
  params['minibatch_frac'] = minibatch_frac
  params['n_estimators'] = n_estimators

  params_output = params.copy()
  params['verbose_eval'] = 1
  params['random_state'] = 1  
  params['verbose'] = False
  #params['natural_gradient']=args.natural

  if BaseType==0:
    params['Base'] = DecisionTreeRegressor(criterion='friedman_mse', max_depth=2)
  elif BaseType == 1:
    params['Base'] = DecisionTreeRegressor(criterion='friedman_mse', max_depth=3)
  elif BaseType == 2:
    params['Base'] = DecisionTreeRegressor(criterion='friedman_mse', max_depth=4)
  elif BaseType == 3:
    params['Base'] = DecisionTreeRegressor(criterion='friedman_mse', max_depth=6)

  #print(**kwargs)

  #arams[''] = {'Base': DecisionTreeRegressor(ccp_alpha=0.0, criterion='mae', max_depth=4,
  #                      max_features=None, max_leaf_nodes=None,
  #                      min_impurity_decrease=0.0, min_impurity_split=None,
  #                      min_samples_leaf=1, min_samples_split=2,
  #                      min_weight_fraction_leaf=0.0, presort='deprecated',
  #                      random_state=None, splitter='best'), 'learning_rate': 0.05, 'minibatch_frac': 1, 'n_estimators': 50, 'verbose_eval': 1, 'random_state': 1}
  #print(params)

  years = [2015,2016,2017]

  predTotal = []
  testTotal = []
  mccs =[]
  Nsamples = 50

  for m in range(len(years)):
    predY = []
    year = years[m]
    x_train,y_train,testX,testY = load_data(year)
    N_days = len(testX.resample('D').sum().values)
    preds_trials = np.zeros((Nsamples,N_days))
    lgb_quantiles_NP_H=np.zeros((1000,len(testX.index),Nsamples))
    lgb_quantiles_NP=np.zeros((1000,N_days,Nsamples))
    predY_AdaptiveThreshold_Sample = np.zeros((1000,N_days,Nsamples))
    preds_Daily = np.zeros((N_days,Nsamples))
    testX_temps = testX['temp']
    testX_Daily = testX_temps#.between_time('7:00','18:00')
    testX_Daily = testX_Daily.resample('D').mean()
    testY_Daily = testY
    testY_Daily = (2*testY_Daily.resample('D').max()+0)/2
    testX_RollingAverages = testX_Daily.rolling(7,min_periods=4).mean()
    testX_AdaptiveThreshold = testY_Daily/(testX_RollingAverages*0.31+21.3)
    #predY_AdaptiveThreshold_Sample_Counted = np.zeros((N_days,50))
    testX_RollingAverages_AdCo = testX_RollingAverages*0.31+21.3
    testY_AdaptiveThreshold= testY_Daily.div(testX_RollingAverages_AdCo,axis=0)

    for k in range(Nsamples):
      ngb = NGBRegressor(**params).fit(x_train, y_train,X_val=testX, Y_val=testY, early_stopping_rounds=2)

      Y_preds = ngb.predict(testX)
      Y_dists = ngb.pred_dist(testX)
      for i in range(1000):
        lgb_quantiles_NP_H[i,:,k] = np.random.normal(loc=Y_dists.loc[:],scale=Y_dists.scale[:])

      preds_Hourly = pd.DataFrame(data=lgb_quantiles_NP_H[:,:,k].T,index=testX.index)
      preds_Hourly.tail()
      preds_Daily = preds_Hourly.resample('D').max()

      for j in range(N_days):
          lgb_quantiles_NP[:,j,k] = preds_Daily.iloc[j]
      for i in range(1000):
          predY_AdaptiveThreshold_Sample[i,:,k] = np.array((lgb_quantiles_NP[i,:,k]/testX_RollingAverages_AdCo.values)>cutoff)*1

    for i in range(N_days):
      predY.append(np.mean(predY_AdaptiveThreshold_Sample[:,i,:]))
    predTotal.append(predY)
    testTotal.append(testY_AdaptiveThreshold.values)

  predTotal = [item for items in predTotal for item in items]
  testTotal = [item for items in testTotal for item in items]

  from sklearn.metrics import accuracy_score, precision_score, recall_score, roc_auc_score, f1_score
  try:
    acc_score = accuracy_score( ((np.array(testTotal)>1)*1),(np.array(predTotal)>factor)*1)
  except:
    acc_score = 0
  try:
    prec_score = precision_score( ((np.array(testTotal)>1)*1),(np.array(predTotal)>factor)*1)
  except:
    prec_score = 0
  try:
    rec_score = recall_score( ((np.array(testTotal)>1)*1),(np.array(predTotal)>factor)*1)
  except:
    rec_score = 0
  try:
    roc_auc_score = roc_auc_score( ((np.array(testTotal)>1)*1),(np.array(predTotal)>factor)*1)
  except:
    roc_auc_score = 0
  try:
    f1_score = f1_score( ((np.array(testTotal)>1)*1),(np.array(predTotal)>factor)*1)
  except: 
    f1_score = 0
  from sklearn.metrics import matthews_corrcoef
  mcc_score = matthews_corrcoef( ((np.array(testTotal)>1)*1),(np.array(predTotal)>factor)*1)
  print("Test Accuracy score: ", acc_score)
  print("Test Precision score: ", prec_score)
  print("Test Recall score: ", rec_score)
  print("Test ROC AUC score: ", roc_auc_score)
  print("Test F1 score: ", f1_score)
  print("Test MCC score: ", mcc_score)
  #mccs.append(mcc_score)

  #mcc_min = np.mean(mccs)#-np.std(mccs)
  params_output['cutoff'] = cutoff
  params_output['factor'] = factor
  params_output['BaseType'] = BaseType
  params_output['T_correct'] = T_correct
  reportedResults = []
  for key, value in params_output.items():
        reportedResults.append(value)

  print("Score: " + str(mcc_score))
  reportedResults.append(mcc_score)
  published=0
  while published==0:
      try:
            append_list_as_row('optimization_log.csv',reportedResults)
            published=1
      except:
            published=0

  return mcc_score#,predTotal,testY_Daily


In [12]:
from csv import writer
def append_list_as_row(file_name, list_of_elem):
    # Open file in append mode
    with open(file_name, 'a+', newline='') as write_obj:
        # Create a writer object from csv module
        csv_writer = writer(write_obj)
        # Add contents of list as last row in the csv file
        csv_writer.writerow(list_of_elem)
def write_new_file(file_name, list_of_elem):
    # Open file in append mode
    with open(file_name, 'w+', newline='') as write_obj:
        # Create a writer object from csv module
        csv_writer = writer(write_obj)
        # Add contents of list as last row in the csv file
        csv_writer.writerow(list_of_elem)

In [15]:
param_grid = {}

param_grid = {
    'learning_rate':[0.05,0.075,0.1,0.125,0.15,0.175,0.2,0.25,0.3,0.4,0.5],
    'minibatch_frac':[0.5,1.0],
    'n_estimators':[20,30,35,40,50]
}
param_grid['cutoff'] = [1.01,1.015,1.02,1.025]
param_grid['factor'] = [0.4,0.5,0.6]
param_grid['BaseType'] = [0,1,2,3]
param_grid['T_correct'] = [0,0.25,0.5,0.75,1,1.25,1.5]

In [13]:
param_grid = {}

param_grid = {
    'learning_rate':[0.25],
    'minibatch_frac':[0.5],
    'n_estimators':[40]
}
param_grid['cutoff'] = [1.01]
param_grid['BaseType'] = [2]
param_grid['T_correct'] = [0]

In [ ]:
#(learning_rate,minibatch_frac,n_estimators,cutoff,BaseType,T_correct)
RunNGBoost(0.25,0.5,40,1.01,2,0)


In [ ]:
#[0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0]
#[0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

#[0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 1 0 0 1 1 0 0 0 0]
#[0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]

#[0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 1 1 0 0 1 1 0 0 0 0]
#[0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
compile()

reportedResults = []
for key, value in param_grid.items():
    reportedResults.append(key)
write_new_file('optimization_log.csv',reportedResults)

best_params, best_score, score_results, _, _ = maximize(RunNGBoost, param_grid, verbose=False, 
                                                        population_size=100,gene_mutation_prob=0.1, gene_crossover_prob=0.5,
                                                        tournament_size=3, generations_number=10, gene_type=None,
                                                        n_jobs=25, error_score='raise')

num_of_classes: num_of_classes: num_of_classes: num_of_classes: num_of_classes: num_of_classes: num_of_classes: num_of_classes: num_of_classes: num_of_classes:          11 num_of_classes: num_of_classes: num_of_classes: 111num_of_classes: num_of_classes: num_of_classes: num_of_classes: 11num_of_classes: num_of_classes: 11
num_of_classes: 
1  
 

   
 

  
features: features: 
11 features: 1features: features: num_of_classes: 111features: 1num_of_classes: features: num_of_classes: 1features: 1features:   
features: 
 
1  

 
 
   
 
 num_of_classes: ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last

['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'last_windspeed_2']['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_sola

  8.01000000e+00 7.65000000e+00]][[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03
  5.22000000e+00 2.79000000e+00]
 [0.00000000e+00 1.83500000e+01 1.12500000e+02 ... 8.66295985e-03
  7.20000000e+00 5.22000000e+00]
 [0.00000000e+00 1.76250000e+01 1.12500000e+02 ... 9.07753845e-03
  4.32000000e+00 7.20000000e+00]
 ...
 [4.23250000e+02 1.91250000e+01 1.35000000e+02 ... 8.76547632e-03
  8.01000000e+00 1.11600000e+01]
 [4.85500000e+02 1.97500000e+01 1.23750000e+02 ... 9.06359951e-03
  7.65000000e+00 8.01000000e+00]
 [5.38000000e+02 2.09750000e+01 1.29375000e+02 ... 9.44032566e-03
  8.01000000e+00 7.65000000e+00]]input features:
 
input features:

input features:
-------------------- 
input features:
 input features:

--------------------input features:
 input features:
-------------------- 
 --------------------[] input features:
 -------------------- [[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03
  5.22000000e+00 2.79000000e+00]
 [0.00000000e+00 1.835000

  8.01000000e+00 7.65000000e+00]]--------------------
[[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03
  5.22000000e+00 2.79000000e+00]
 [0.00000000e+00 1.83500000e+01 1.12500000e+02 ... 8.66295985e-03
  7.20000000e+00 5.22000000e+00]
 [0.00000000e+00 1.76250000e+01 1.12500000e+02 ... 9.07753845e-03
  4.32000000e+00 7.20000000e+00]
 ...
 [4.23250000e+02 1.91250000e+01 1.35000000e+02 ... 8.76547632e-03
  8.01000000e+00 1.11600000e+01]
 [4.85500000e+02 1.97500000e+01 1.23750000e+02 ... 9.06359951e-03
  7.65000000e+00 8.01000000e+00]
 [5.38000000e+02 2.09750000e+01 1.29375000e+02 ... 9.44032566e-03
  8.01000000e+00 7.65000000e+00]] --------------------
--------------------[[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03
  5.22000000e+00 2.79000000e+00]
 [0.00000000e+00 1.83500000e+01 1.12500000e+02 ... 8.66295985e-03
  7.20000000e+00 5.22000000e+00]
 [0.00000000e+00 1.76250000e+01 1.12500000e+02 ... 9.07753845e-03
  4.32000000e+00 7.20000000e+00]
 ...
 [4

/home/rysanek/jupyter_py3/lib/python3.8/site-packages/evolutionary_search/optimize.py:81: UserWarning: Need to create a creator. Run optimize.compile()
  warnings.warn("Need to create a creator. Run optimize.compile()")


num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'last_windspeed_2']
categorical features:  []
input features:
 [[0.00000000e+00 1.92750000e+01 1.01250000e+02 

features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'last_windspeed_2']
categorical features:  []
input features:
 [[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03


features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'last_windspeed_2']
categorical features:  []
input features:
 [[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03


  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
Test Accuracy score:  0.9050632911392406
Test Precision score:  0.38095238095238093
Test Recall score:  0.8
Test ROC AUC score:  0.856081081081081
Test F1 score:  0.5161290322580645
Test MCC score:  0.5107869843536493
Score: 0.5107869843536493
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'nex

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
Test Accuracy score:  0.9113924050632911
Test Precision score:  0.4166666666666667
Test Recall score:  1.0
Test ROC AUC score:  0.9527027027027026
Test F1 score:  0.5882352941176471
Test MCC score:  0.6142086390244379
Score: 0.6142086390244379
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'nex

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
Test Accuracy score:  0.9240506329113924
Test Precision score:  0.4444444444444444
Test Recall score:  0.8
Test ROC AUC score:  0.8662162162162164
Test F1 score:  0.5714285714285714
Test MCC score:  0.5613040219544173
Score: 0.5613040219544173
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'nex

features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'last_windspeed_2']
categorical features:  []
input features:
 [[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03


  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  6.39000000e+00 3.96000000e+00]]
num_of_classes: -------------------- 1

features: output:
 ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'last_windspeed_2'] [26.32 26.1  25.9  ... 24.8

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
Test Accuracy score:  0.9493670886075949
Test Precision score:  0.5833333333333334
Test Recall score:  0.7
Test ROC AUC score:  0.8331081081081081
Test F1 score:  0.6363636363636365
Test MCC score:  0.6123207915956418
Score: 0.6123207915956418
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'nex

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
Test Accuracy score:  0.9367088607594937
Test Precision score:  0.5
Test Recall score:  0.6
Test ROC AUC score:  0.7797297297297298
Test F1 score:  0.5454545454545454
Test MCC score:  0.5142004213399507
Score: 0.5142004213399507
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'nex

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
Test Accuracy score:  0.8734177215189873
Test Precision score:  0.3076923076923077
Test Recall score:  0.8
Test ROC AUC score:  0.8391891891891892
Test F1 score:  0.4444444444444444
Test MCC score:  0.445481030407972
Score: 0.445481030407972
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_

Test Recall score:  0.8
Test ROC AUC score:  0.8729729729729729
Test F1 score:  0.6153846153846154
Test MCC score:  0.6020520675524309
Score: 0.6020520675524309
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
Test Accuracy score:  0.9556962025316456
Test Precision score:  0.6363636363636364
Test Recall score:  0.7
Test ROC AUC score:  0.8364864864864865
Test F1 score:  0.6666666666666666
Test MCC score:  0.6438333526231438
Score: 0.6438333526231438
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'nex

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
Test Accuracy score:  0.8670886075949367
Test Precision score:  0.3225806451612903
Test Recall score:  1.0
Test ROC AUC score:  0.9290540540540541
Test F1 score:  0.4878048780487805
Test MCC score:  0.5261264744637432
Score: 0.5261264744637432
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'nex

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
Test Accuracy score:  0.9177215189873418
Test Precision score:  0.42105263157894735
Test Recall score:  0.8
Test ROC AUC score:  0.8628378378378379
Test F1 score:  0.5517241379310345
Test MCC score:  0.543236851002992
Score: 0.543236851002992
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
Test Accuracy score:  0.9240506329113924
Test Precision score:  0.4444444444444444
Test Recall score:  0.8
Test ROC AUC score:  0.8662162162162164
Test F1 score:  0.5714285714285714
Test MCC score:  0.5613040219544173
Score: 0.5613040219544173
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'nex

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
Test Accuracy score:  0.930379746835443
Test Precision score:  0.47058823529411764
Test Recall score:  0.8
Test ROC AUC score:  0.8695945945945945
Test F1 score:  0.5925925925925927
Test MCC score:  0.5808345573834994
Score: 0.5808345573834994
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'nex

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
Test Accuracy score:  0.8987341772151899
Test Precision score:  0.38461538461538464
Test Recall score:  1.0
Test ROC AUC score:  0.9459459459459459
Test F1 score:  0.5555555555555556
Test MCC score:  0.585692191373031
Score: 0.585692191373031
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
Test Accuracy score:  0.930379746835443
Test Precision score:  0.47368421052631576
Test Recall score:  0.9
Test ROC AUC score:  0.9162162162162162
Test F1 score:  0.6206896551724138
Test MCC score:  0.6231543765695402
Score: 0.6231543765695402
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'nex

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
Test Accuracy score:  0.9620253164556962
Test Precision score:  0.7
Test Recall score:  0.7
Test ROC AUC score:  0.8398648648648649
Test F1 score:  0.7
Test MCC score:  0.6797297297297298
Score: 0.6797297297297298
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'las

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
Test Accuracy score:  0.9430379746835443
Test Precision score:  0.5555555555555556
Test Recall score:  0.5
Test ROC AUC score:  0.7364864864864866
Test F1 score:  0.5263157894736842
Test MCC score:  0.49688146120428156
Score: 0.49688146120428156
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'n

['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'last_windspeed_2']  1input features:

 ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_rad

  8.01000000e+00 7.65000000e+00]]

--------------------output:

 output:
 output:
input features:
[26.32 26.1  25.9  ... 24.84 24.84 24.64] [26.32 26.1  25.9  ... 22.74 23.17 23.67] 

output:
[26.32 26.1  25.9  ... 24.84 24.84 24.64]
[[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03
  5.22000000e+00 2.79000000e+00]
 [0.00000000e+00 1.83500000e+01 1.12500000e+02 ... 8.66295985e-03
  7.20000000e+00 5.22000000e+00]
 [0.00000000e+00 1.76250000e+01 1.12500000e+02 ... 9.07753845e-03
  4.32000000e+00 7.20000000e+00]
 ...
 [4.23250000e+02 1.91250000e+01 1.35000000e+02 ... 8.76547632e-03
  8.01000000e+00 1.11600000e+01]
 [4.85500000e+02 1.97500000e+01 1.23750000e+02 ... 9.06359951e-03
  7.65000000e+00 8.01000000e+00]
 [5.38000000e+02 2.09750000e+01 1.29375000e+02 ... 9.44032566e-03
  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
input features:
 
[[0.00000000e+00 1.92750000e+01 1

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'last_windspeed_2']
categorical features:  []
input features:
 [[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03


  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
Test Accuracy score:  0.9240506329113924
Test Precision score:  0.4375
Test Recall score:  0.7
Test ROC AUC score:  0.8195945945945946
Test F1 score:  0.5384615384615384
Test MCC score:  0.5158888187541664
Score: 0.5158888187541664
Test Accuracy score:  0.9050632911392406
Test Precision score:  0.3684210526315789
Test Recall score:  0.7
Test ROC AUC score:  0.8094594594594594
Test F1 score:  0.48275862068965514
Test MCC score:  0.46331932543644383
Score: 0.46331932543644383
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_tem

  features:    ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'last_windspeed_2']       ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_ra

['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'last_windspeed_2']['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_sola

  8.01000000e+00 7.65000000e+00]][[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03
  5.22000000e+00 2.79000000e+00]
 [0.00000000e+00 1.83500000e+01 1.12500000e+02 ... 8.66295985e-03
  7.20000000e+00 5.22000000e+00]
 [0.00000000e+00 1.76250000e+01 1.12500000e+02 ... 9.07753845e-03
  4.32000000e+00 7.20000000e+00]
 ...
 [4.23250000e+02 1.91250000e+01 1.35000000e+02 ... 8.76547632e-03
  8.01000000e+00 1.11600000e+01]
 [4.85500000e+02 1.97500000e+01 1.23750000e+02 ... 9.06359951e-03
  7.65000000e+00 8.01000000e+00]
 [5.38000000e+02 2.09750000e+01 1.29375000e+02 ... 9.44032566e-03
  8.01000000e+00 7.65000000e+00]][[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03
  5.22000000e+00 2.79000000e+00]
 [0.00000000e+00 1.83500000e+01 1.12500000e+02 ... 8.66295985e-03
  7.20000000e+00 5.22000000e+00]
 [0.00000000e+00 1.76250000e+01 1.12500000e+02 ... 9.07753845e-03
  4.32000000e+00 7.20000000e+00]
 ...
 [4.23250000e+02 1.91250000e+01 1.35000000e+02 ... 8.76547632e-03


  8.01000000e+00 7.65000000e+00]][[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03
  5.22000000e+00 2.79000000e+00]
 [0.00000000e+00 1.83500000e+01 1.12500000e+02 ... 8.66295985e-03
  7.20000000e+00 5.22000000e+00]
 [0.00000000e+00 1.76250000e+01 1.12500000e+02 ... 9.07753845e-03
  4.32000000e+00 7.20000000e+00]
 ...
 [4.23250000e+02 1.91250000e+01 1.35000000e+02 ... 8.76547632e-03
  8.01000000e+00 1.11600000e+01]
 [4.85500000e+02 1.97500000e+01 1.23750000e+02 ... 9.06359951e-03
  7.65000000e+00 8.01000000e+00]
 [5.38000000e+02 2.09750000e+01 1.29375000e+02 ... 9.44032566e-03
  8.01000000e+00 7.65000000e+00]][[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03
  5.22000000e+00 2.79000000e+00]
 [0.00000000e+00 1.83500000e+01 1.12500000e+02 ... 8.66295985e-03
  7.20000000e+00 5.22000000e+00]
 [0.00000000e+00 1.76250000e+01 1.12500000e+02 ... 9.07753845e-03
  4.32000000e+00 7.20000000e+00]
 ...
 [4.23250000e+02 1.91250000e+01 1.35000000e+02 ... 8.76547632e-03


features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'last_windspeed_2']
categorical features:  []
input features:
 [[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03


features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'last_windspeed_2']
categorical features:  []
input features:
input features:
  [[0.00000000e+00 1.92750000e+01 1.01250000e+02 ..

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
Test Accuracy score:  0.9050632911392406
Test Precision score:  0.391304347826087
Test Recall score:  0.9
Test ROC AUC score:  0.9027027027027026
Test F1 score:  0.5454545454545454
Test MCC score:  0.5560509607327384
Score: 0.5560509607327384
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
Test Accuracy score:  0.9177215189873418
Test Precision score:  0.43478260869565216
Test Recall score:  1.0
Test ROC AUC score:  0.9560810810810811
Test F1 score:  0.6060606060606061
Test MCC score:  0.629755702172145
Score: 0.629755702172145
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next

  6.39000000e+00 3.96000000e+00]]

--------------------
output:
 Test Precision score:  0.5263157894736842
Test Recall score:  1.0
[26.32 26.1  25.9  ... 24.84 24.84 24.64]Test ROC AUC score: 
 0.9695945945945945
Test F1 score:  0.6896551724137931
Test MCC score:  0.7030719021360884
Score: 0.7030719021360884
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
Test Accuracy score:  0.9556962025316456
Test Precision score:  0.6363636363636364
Test Recall score:  0.7
Test ROC AUC score:  0.8364864864864865
Test F1 score:  0.6666666666666666
Test MCC score:  0.6438333526231438
Score: 0.6438333526231438
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'nex

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------Test Precision score: 
 output:
0.42857142857142855 
[26.32 26.1  25.9  ... 22.74 23.17 23.67]Test Recall score: 
 0.9
Test ROC AUC score:  0.9094594594594593
Test F1 score:  0.5806451612903225
Test MCC score:  0.5873565702434753
Score: 0.5873565702434753
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  8.01000000e+00 7.65000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 22.74 23.17 23.67]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'last_windspeed_2']
categorical features:  []
input features:
 [[0.00000000e+00 1.92750000e+01 1.01250000e+02 ... 8.34082224e-03


  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
num_of_classes:  1
features:  ['solar_radiation', 'temp', 'wind_dir', 'hum_ratio', 'windspeed', 'weekday', 'week', 'last_solar_radiation_1', 'last_solar_radiation_2', 'last_solar_radiation_3', 'last_solar_radiation_4', 'last_solar_radiation_5', 'last_solar_radiation_6', 'last_temp_1', 'last_temp_2', 'last_temp_3', 'last_temp_4', 'last_temp_5', 'last_temp_6', 'last_temp_7', 'last_temp_8', 'last_temp_9', 'last_temp_10', 'last_temp_11', 'last_temp_12', 'last_temp_13', 'last_temp_14', 'last_temp_15', 'last_temp_16', 'last_temp_17', 'last_temp_18', 'last_temp_19', 'last_temp_20', 'last_temp_21', 'last_temp_22', 'last_temp_23', 'last_temp_24', 'next_temp_1', 'next_temp_2', 'last_wind_dir_1', 'last_wind_dir_2', 'last_wind_dir_3', 'last_wind_dir_4', 'next_wind_dir_1', 'next_wind_dir_2', 'last_hum_ratio_1', 'last_hum_ratio_2', 'last_hum_ratio_3', 'last_hum_ratio_4', 'last_windspeed_1', 'las

  6.39000000e+00 3.96000000e+00]]
--------------------
output:
 [26.32 26.1  25.9  ... 24.84 24.84 24.64]
Test Accuracy score:  0.930379746835443
Test Precision score:  0.47368421052631576
Test Recall score:  0.9
Test ROC AUC score:  0.9162162162162162
Test F1 score:  0.6206896551724138
Test MCC score:  0.6231543765695402
Score: 0.6231543765695402
Test Accuracy score:  0.9556962025316456
Test Precision score:  0.7142857142857143
Test Recall score:  0.5
Test ROC AUC score:  0.7432432432432433
Test F1 score:  0.588235294117647
Test MCC score:  0.5756574705799479
Score: 0.5756574705799479
Test Accuracy score:  0.9493670886075949
Test Precision score:  0.625
Test Recall score:  0.5
Test ROC AUC score:  0.7398648648648648
Test F1 score:  0.5555555555555556
Test MCC score:  0.532766449854052
Score: 0.532766449854052
Test Accuracy score:  0.930379746835443
Test Precision score:  0.4666666666666667
Test Recall score:  0.7
Test ROC AUC score:  0.822972972972973
Test F1 score:  0.56
Test MCC sco

In [ ]:
best_params

In [ ]:
pwdir